#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#########################
# split file load
#########################
source ~/.zsh/000_general.zsh
source ~/.zsh/100_prompt.zsh
source ~/.zsh/200_aliases.zsh
source ~/.zsh/300_env.zsh
source ~/.zsh/400_function.zsh
